import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeContext } from "@/context/ThemeContext";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import { ShopContext } from "@/context/ShopContext";
import { LanguageSwitcherProvider } from "@/context/LanguageContext";
import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{ display: "flex" }}>
          {/* Sidebar */}
          <nav style={sidebarStyle}>
            <Link href={"/"} style={linkStyle}>
              Home
            </Link>
            <Link href={"/assignment-1"} style={linkStyle}>
              Assignment 1
            </Link>
            <Link href={"/assignment-2"} style={linkStyle}>
              Assignment 2
            </Link>
            <Link href={"/assignment-3"} style={linkStyle}>
              Assignment 3
            </Link>
            
            <Link href={"/assignment-4"} style={linkStyle}>
              Assignment 4
            </Link>
            <Link href={"/"} style={linkStyle}>
              Assignment 5
            </Link>
            <Link href={"/"} style={linkStyle}>
              Assignment 6
            </Link>
            <p style={{ marginTop: "40px" }}></p>
            <hr></hr>

            <Link href={"/about"} style={linkStyle}>
              about
            </Link>
            <Link href={"/dashboard"} style={linkStyle}>
              dashboard
            </Link>
            <Link href={"/profile"} style={linkStyle}>
              profile
            </Link>
            <Link href={"/settings"} style={linkStyle}>
              setting
            </Link>
          </nav>

          {/* Main content */}
          <main style={{ flex: 1, padding: "20px" }}>
            <ThemeContext>
              <ThemeSwitcher />
              <ShopContext>
                <LanguageSwitcherProvider>
                  <AuthContextProvider>{children}</AuthContextProvider>
                </LanguageSwitcherProvider>
              </ShopContext>
            </ThemeContext>
          </main>
        </div>
      </body>
    </html>
  );
}

const sidebarStyle = {
  width: "200px",
  height: "100vh",
  backgroundColor: "#f0f0f0",
  padding: "20px",
  boxSizing: "border-box",
  display: "flex",
  flexDirection: "column",
  gap: "10px",
};

const linkStyle = {
  textDecoration: "none",
  color: "#333",
  fontWeight: "500",
  padding: "8px",
  borderRadius: "4px",
  backgroundColor: "#e0e0e0",
  transition: "background 0.3s",
};
