import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <div>
     <Link href="/assignment-1/ques1">
        <button>ques1</button>
      </Link>
      <Link href="/assignment-1/ques2">
        <button>ques2</button>
      </Link>
      <Link href="/assignment-1/ques3">
        <button>ques3</button>
      </Link>
      <Link href="/assignment-1/ques4">
        <button>ques4</button>
      </Link>
      <Link href="/assignment-1/ques5">
        <button>ques5</button>
      </Link>
      <Link href="/assignment-1/ques6">
        <button>ques6</button>
      </Link>
      
     </div>
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
